---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.10.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "AMy04MPNLZ7x9c5uECAOykvm4Epulpnfze/75EVP4732UJKLjIoXXARYx/6V7PKVcq5pFxgaINXndvfkqrgjSUEBDzyEqVK7pjlbbIqnUzRptYXQvXti840fJ2eL+JODdaexaF0rtThMtzx34E5gqzJLi0eLdvRONQM7FEXPxKI1rflP1bttEIeFGy2RMmIJUO6X7ob/ryrRS0MZnwc6bmZ+Vl9dMiMbWnCUlqGYUJtyO6fkdPe65QiRcyjAWIjnINtVm+VTM+XQdQGZMHZW5esUn5foX5SECypz2VdduA/8GyBuijfe/ntd42xs2/RkNYvrLH3yJEw2kIHLg52nWxcCDAIYJYhjojEL5alxbkcYPAbeJeByUZGNwx1jSo2SWfCJqMYNFH6+3SREGM9kKNP12IBf305fLUIFVXSfA7J/mxs6dmXB4s4T5PbuU7s6jeDyaepk5o0f3GqclZMHe0b7YWWXPo761ZHHpTj8EvYdjGFSV0ElirHmXErknBgQUXF6OPMqXGfGtidWZlaZ1GRdyo0VIkVrPNSObxtzr2jIJXjrPpHh+OBue06npvscoKtW6aM8r3wA+ZNBh09NbSQ84PgHAU6kQkcBEP1D5uzkz+LyGkoB8A3G0C5E+1d3Pn1/rijZ3cxpCVGPjChQPvh7/aSWX5Cjlvnzpc3x5Yw="
    file:
      - cross/ship-linux-amd64.md5
      - cross/ship-windows-386.sha256
      - cross/ship-linux-arm
      - cross/ship-darwin-amd64.md5
      - cross/ship-darwin-amd64
      - cross/ship-solaris-amd64.md5
      - cross/ship-linux-arm64.sha256
      - cross/ship-linux-arm.sha256
      - cross/ship-linux-386.sha256
      - cross/ship-darwin-386.md5
      - cross/ship-windows-386.md5
      - cross/ship-freebsd-amd64.md5
      - cross/ship-linux-arm64.md5
      - cross/ship-linux-arm64
      - cross/ship-freebsd-amd64.sha256
      - cross/ship-freebsd-386.md5
      - cross/ship-linux-amd64.sha256
      - cross/ship-linux-386.md5
      - cross/ship-freebsd-386
      - cross/ship-solaris-amd64.sha256
      - cross/ship-windows-amd64
      - cross/ship-windows-amd64.md5
      - cross/ship-windows-amd64.sha256
      - cross/ship-linux-arm.md5
      - cross/ship-darwin-386.sha256
      - cross/ship-darwin-amd64.sha256
      - cross/ship-windows-386
      - cross/ship-solaris-amd64
      - cross/ship-darwin-386
      - cross/ship-linux-386
      - cross/ship-freebsd-amd64
      - cross/ship-freebsd-386.sha256
      - cross/ship-linux-amd64
    skip_cleanup: true
    on:
      tags: true
